all:
  children:
    laptops:
      hosts:
        e14:
          ansible_host: "{{ vault_e14_host }}"
    servers:
      hosts:
        raspberrypi:
          ansible_host: "{{ vault_rpi_host }}"
    desktops:
      hosts:
        tsunami:
          ansible_host: 192.168.2.14
